### ISSUE TITLE
WebSite - Show unroutable files

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#293] opened 2013-10-23 18:31 UTC
Original Savannah ticket 28628 reported by None on Wed Aug  8 14:53:12 2007.

Lassi brings us this idea, which I think is a good one:

1) for the block status / delay table you were showing, including files that have a t_xfer_request but no t_xfer_path (= unrouteable), since i guess there's now fair chance to have such files

**Comment by nikmagini** [comment] 2015-07-02 15:23
Duplicate of https://github.com/dmwm/PHEDEX/issues/615 - closing, see other ticket for details.

**Closed by nikmagini** 2015-07-02 15:23 UTC
Labels: Category: Web page, Priority 3: Normal
