### ISSUE TITLE
Unexpected 'insufficient privileges' error for CENTRAL role

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#938] opened 2013-10-23 19:04 UTC
Original Savannah ticket 102274 reported by wildish on Fri Aug 16 11:16:46 2013.

Hello,

the PHEDEX_CENTRAL_DEBUG role gets an &quot;insufficient privileges&quot; error when trying to update t_dps_dataset, despite having UPDATE privilege on all tables including t_dps_dataset. Example:

+verbatim+
&gt; echo &quot;update t_dps_dataset set is_open = 'y' where name = 'PhEDEx_Debug/LoadTest07Source/IN_TIFR';&quot; | sqlplus -S $(PHEDEX/Utilities/OracleConnectId -db /data/DBAccessInfo/DBParam:Debug/CENTRAL)
update t_dps_dataset set is_open = 'y' where name = '/PhEDEx_Debug/LoadTest07Source/IN_TIFR'
        *
ERROR at line 1:
ORA-01031: insufficient privileges 
-verbatim-

+verbatim+

SQL&gt; select * from role_tab_privs where role='PHEDEX_CENTRAL_DEBUG' and table_name='T_DPS_DATASET';

ROLE                           OWNER TABLE_NAME COLUMN_NAME PRIVILEGE                                GRA
------------------------------ ------------------------------ ------------------------------ ------------------------------ ---------------------------------------- ---
PHEDEX_CENTRAL_DEBUG           CMS_TRANSFERMGMT_SC T_DPS_DATASET FLASHBACK                                NO
PHEDEX_CENTRAL_DEBUG           CMS_TRANSFERMGMT_SC T_DPS_DATASET UPDATE                                   NO
PHEDEX_CENTRAL_DEBUG           CMS_TRANSFERMGMT_SC T_DPS_DATASET DELETE                                   NO
PHEDEX_CENTRAL_DEBUG           CMS_TRANSFERMGMT_SC T_DPS_DATASET INSERT                                   NO
PHEDEX_CENTRAL_DEBUG           CMS_TRANSFERMGMT_SC T_DPS_DATASET SELECT                                   NO
-verbatim-

Cheers
Nicolo'

**Comment by nikmagini** [comment] 2016-10-19 13:43
Probably caused by failing to set the proper role before executing the SQL. Closing.

**Closed by nikmagini** 2016-10-19 13:43 UTC
Labels: Category: Command-line Tools, Priority 3: Normal, Status: Unreproducible
